# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SH_Utils' do
    #    pod 'SH_Utils' :path=>'../'
    pod 'SH_Utils' , :git =>'https://github.com/wshcocoapods/UIKit.git'

end
